#!/usr/bin/env bash
#
# Build example 05 with colcon and launch it, inside a ROS 2 workspace.
#
# Usage:
#   examples/05_ros2_control/run.sh [--seconds N] [ros2 launch arguments...]
#
#   --seconds N  Run the launch for N seconds, then stop it and print the
#                joint positions sampled near the start and at the end.  That
#                pair is the evidence the controller was active and the arm
#                moved.  Without it the launch runs until Ctrl-C.
#
#   Everything else is passed through to `ros2 launch`.
#
# The artifact is not exported here: it belongs to the machine that will run
# it, and the interpreter that writes it (JAX) is not in the ROS image.  Run
# `make export` on the host first; the container sees it through the bind
# mount.
#
# Everything colcon writes goes under build/ros2/, which is already gitignored
# along with the rest of build/.

set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && [[ $# -eq 1 ]]; then
  # The header comment is the help text; stopping at the first non-comment
  # line means there is no line range to keep in step with edits.
  awk 'NR > 1 && /^#/ { print; next } NR > 1 { exit }' "$0"
  exit 0
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

BUILD="build/ros2"
LOG="$BUILD/launch.log"
ARTIFACT="artifacts/arm"

seconds=""
launch_args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seconds) seconds="${2:?--seconds needs a number}"; shift 2 ;;
    --seconds=*) seconds="${1#*=}"; shift ;;
    *) launch_args+=("$1"); shift ;;
  esac
done

for tool in colcon ros2; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "no $tool on PATH: run this inside a ROS 2 workspace, or through" >&2
    echo "  docker compose -f docker/compose.yml run --rm ros2 $0" >&2
    exit 1
  }
done

if [[ ! -f "$ARTIFACT.json" ]]; then
  echo "no $ARTIFACT.json: run \`make export\` on this machine first" >&2
  exit 1
fi

echo "=== colcon build (jax_arm_controller) ==="
colcon --log-base "$BUILD/log" build \
  --base-paths examples/05_ros2_control \
  --packages-select jax_arm_controller \
  --build-base "$BUILD/build" \
  --install-base "$BUILD/install"

# `set -u` off across the source: colcon's generated setup.bash reads
# $COLCON_TRACE without a default and would abort the script on it.
set +u
# shellcheck disable=SC1091  # generated by the build above, not in the tree
source "$BUILD/install/setup.bash"
set -u

if [[ -z "$seconds" ]]; then
  echo
  echo "=== ros2 launch jax_arm_controller arm.launch.py ==="
  exec ros2 launch jax_arm_controller arm.launch.py "${launch_args[@]}"
fi

# One JointState position vector, or nothing when the topic is not publishing
# yet.  `--once` returns as soon as a message arrives, and prints the field as
# a Python `array('d', [...])`; the bracketed part is the whole of it, and the
# sed also drops the lost-message warning `ros2 topic echo` writes to stdout.
sample() {
  timeout 15 ros2 topic echo --once --field position /joint_states 2>/dev/null |
    sed -n 's/.*\[\(.*\)\].*/\1/p' | head -1
}

# Sampling runs beside the launch rather than after it: the interesting pair is
# the first vector published and the last one before shutdown, and both are
# gone once the nodes are down.
sample_until_killed() {
  local positions
  while :; do
    positions="$(sample)"
    if [[ -n "$positions" ]]; then
      [[ -s "$BUILD/first.txt" ]] || printf '%s\n' "$positions" >"$BUILD/first.txt"
      printf '%s\n' "$positions" >"$BUILD/last.txt"
    fi
    sleep 1
  done
}

echo
echo "=== ros2 launch jax_arm_controller arm.launch.py (${seconds}s) ==="
rm -f "$BUILD/first.txt" "$BUILD/last.txt"
sample_until_killed &
sampler=$!

# In the foreground, under `timeout`, and never backgrounded: a background job
# in a non-interactive shell has SIGINT set to ignore, which it passes on to
# every node the launch starts, and the run then cannot be stopped.  `timeout`
# puts the launch in its own process group and signals the group.
timeout --signal=INT --kill-after=15 "$seconds" \
  ros2 launch jax_arm_controller arm.launch.py "${launch_args[@]}" \
  >"$LOG" 2>&1 || true

kill "$sampler" 2>/dev/null || true
wait "$sampler" 2>/dev/null || true

cat "$LOG"
echo
echo "=== /joint_states ==="
echo "first $(cat "$BUILD/first.txt" 2>/dev/null || echo '<nothing published>')"
echo "last  $(cat "$BUILD/last.txt" 2>/dev/null || echo '<nothing published>')"
