#!/usr/bin/env bash
#
# Build example 05 with colcon and launch it, inside a ROS 2 workspace.
#
# Usage:
#   examples/05_ros2_control/run.sh [--seconds N] [ros2 launch arguments...]
#
#   --seconds N  Run the launch for N seconds, stop it, and print the joint
#                positions sampled near the start and at the end.  The exit
#                status is then non-zero unless the log shows both hardening
#                lines and the controller's activation, and the two position
#                vectors were published and differ -- the same four facts
#                tests/test_examples_ros2.py checks.  Without --seconds the
#                launch runs until Ctrl-C.
#
#   Everything else is passed through to `ros2 launch`.
#
# The artifact is not exported here: it belongs to the machine that will run
# it, and JAX is not in the ROS image.  Run `make export` on the host first;
# the container sees it through the bind mount.  Everything colcon writes goes
# under build/ros2/.

set -euo pipefail

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]] && [[ $# -eq 1 ]]; then
  awk 'NR > 1 && /^#/ { print; next } NR > 1 { exit }' "$0"  # the header
  exit 0
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

BUILD="build/ros2"
LOG="$BUILD/launch.log"
ARTIFACT="artifacts/arm"

seconds=""
launch_args=()
while [[ $# -gt 0 ]]; do
  case "$1" in
    --seconds) seconds="${2:?--seconds needs a number}"; shift 2 ;;
    --seconds=*) seconds="${1#*=}"; shift ;;
    *) launch_args+=("$1"); shift ;;
  esac
done

for tool in colcon ros2; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "no $tool on PATH: run this inside a ROS 2 workspace, or through" >&2
    echo "  docker compose -f docker/compose.yml run --rm ros2 $0" >&2
    exit 1
  }
done

if [[ ! -f "$ARTIFACT.json" ]]; then
  echo "no $ARTIFACT.json: run \`make export\` on this machine first" >&2
  exit 1
fi

echo "=== colcon build (jax_arm_controller) ==="
colcon --log-base "$BUILD/log" build \
  --base-paths examples/05_ros2_control \
  --packages-select jax_arm_controller \
  --build-base "$BUILD/build" \
  --install-base "$BUILD/install"

# colcon's generated setup.bash reads $COLCON_TRACE without a default.
set +u
# shellcheck disable=SC1091  # generated by the build above, not in the tree
source "$BUILD/install/setup.bash"
set -u

if [[ -z "$seconds" ]]; then
  echo
  echo "=== ros2 launch jax_arm_controller arm.launch.py ==="
  exec ros2 launch jax_arm_controller arm.launch.py "${launch_args[@]}"
fi

# One JointState position vector, or nothing while the topic is silent.
# The type is given so `--once` waits for the topic instead of failing while
# it is absent; `|| true` keeps `set -e` from ending the background loop on
# the 15 s timeout; the sed keeps the bracketed part of the `array('d', [...])`
# line and nothing else -- the not-yet-published warning also carries brackets.
sample() {
  timeout 15 ros2 topic echo --once --field position /joint_states \
      sensor_msgs/msg/JointState 2>/dev/null |
    sed -n 's/^array(.*\[\(.*\)\]).*/\1/p' | head -1 || true
}

# Beside the launch rather than after it: the first vector published and the
# last one before shutdown are both gone once the nodes are down.
sample_until_killed() {
  local positions
  while :; do
    positions="$(sample)"
    if [[ -n "$positions" ]]; then
      [[ -s "$BUILD/first.txt" ]] || echo "$positions" >"$BUILD/first.txt"
      echo "$positions" >"$BUILD/last.txt"
    fi
    sleep 1
  done
}

# The loop, and the `ros2 topic echo` it may be inside.  Each command guarded:
# under `set -e` a failing one in the EXIT trap becomes the exit status.
stop_sampler() {
  pkill -P "$sampler" 2>/dev/null || true
  kill "$sampler" 2>/dev/null || true
}

echo
echo "=== ros2 launch jax_arm_controller arm.launch.py (${seconds}s) ==="
rm -f "$BUILD/first.txt" "$BUILD/last.txt"
sample_until_killed &
sampler=$!
trap stop_sampler EXIT  # on a signal too, so no loop is left behind

# In the foreground, never backgrounded: a background job in a non-interactive
# shell ignores SIGINT, every node inherits that, and the run cannot be
# stopped.  `timeout` puts the launch in its own process group and signals it.
timeout --signal=INT --kill-after=15 "$seconds" \
  ros2 launch jax_arm_controller arm.launch.py "${launch_args[@]}" \
  >"$LOG" 2>&1 || true

stop_sampler
wait "$sampler" 2>/dev/null || true

cat "$LOG"
echo
echo "=== /joint_states ==="
echo "first $(cat "$BUILD/first.txt" 2>/dev/null || echo '<nothing published>')"
echo "last  $(cat "$BUILD/last.txt" 2>/dev/null || echo '<nothing published>')"

status=0
for step in harden_malloc lock_memory; do
  if ! grep -q "\] $step:" "$LOG"; then
    echo "FAIL: no $step status line" >&2
    status=1
  fi
done
if ! grep -q 'Configured and activated jax_arm_controller' "$LOG"; then
  echo "FAIL: jax_arm_controller never activated" >&2
  status=1
fi
if [[ ! -s "$BUILD/first.txt" || ! -s "$BUILD/last.txt" ]] ||
   cmp -s "$BUILD/first.txt" "$BUILD/last.txt"; then
  echo "FAIL: the joints did not move" >&2
  status=1
fi
exit "$status"
